### ISSUE TITLE
How to update it?

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/bromitewebview#29] opened 2021-02-17 12:37 UTC
A few days ago Bromite released an update for browser and webkit.
How to update it?
Readme says:

> to update it just reflash the module

But when module is reflashed it reports the version is the same and simply uninstalls.

So what I have to do? Uninstall - reboot - install - reboot for the simple update?

By the way Playmarket also reports about update - there is no information should official webkit be not updated in Playmarket or not.

**Comment by androidacy** [comment] 2021-02-20 22:20
You can update the app(s) installed as normal, in theory that'll work fine.

Closing as this is intended behavior (it'll refuse to reinstall itself)

**Closed by androidacy** 2021-02-20 22:20 UTC

**Comment by gjf** [comment] 2021-02-20 23:16
I'd like to - but your module did not add Bromite webkit leaving only Google one. IT simply does not work as intended.
