### ISSUE TITLE
Doesn't support Android 11?

### ISSUE THREAD

**Issue by TuxKruger** [Magisk-Modules-Repo/bromitewebview#18] opened 2020-11-10 05:58 UTC
I flashed the module on LineageOS 18 (Android 11), the terminal(or whatever you call that flashing tab in Magisk Manager) displayed no error or such. It seemed to be installed fine(according to flash logs) so I rebooted and found that no, it is not installed. I am assuming that it is more like a compatibility issue. I hope you fix it in the future release or if there's any workaround for the current release then please let me know.
Device: Redmi Note 9S
OS: LineageOS 18 Android 11

**Comment by unixandria-xda** [comment] 2020-11-28 20:40
Until my primary device gets Android 11 or I get a new device, whichever comes first, I cannot test Android 11 and it's supported on a best case scenario basis.

Will close this issue once I merge proper support

**Comment by Huzaifa-code** [comment] 2020-12-08 12:03
I have successfully installed it . 
But the app is not opening 
I have android 10 , resurrection os

**Comment by TuxKruger** [comment] 2020-12-08 12:19
You are mentioning an android 10 related issue in an android 11 related issue.

**Comment by unixandria-xda** [comment] 2021-01-07 17:27
OxygenOS should be getting beta android eleven in the coming month so I'll test then

**Comment by Master0ne** [comment] 2021-02-19 22:29
I can confirm that `Webview Switcher 7.3.0` (Magisk Module) is not working on Android 11. I have just tested it on my POCO X3 NFC with ArrowOS 11 with the following result:

It installs without error, but after reboot `WebView implementation` in `Developer options` is still showing `Android System WebView 88.0.4324.152` instead of the expected `Bromite System WebView 88.0.4324.185`.

**Comment by ProblematicDude** [comment] 2021-02-20 05:17
I'm also A11 user and it's working fine for me. It might be your ROM issue. Contact your maintainer may be.


![Current Webview](https://user-images.githubusercontent.com/59223300/108584631-f0485f80-7368-11eb-80d2-967cca7a0d93.png)

![A version](https://user-images.githubusercontent.com/59223300/108584633-f63e4080-7368-11eb-8cda-7d7255f48697.png)

**Comment by Master0ne** [comment] 2021-02-20 05:29
> I'm also A11 user and it's working fine for me. It might be your ROM issue. Contact your maintainer may be.

It's odd but as it seems different ROMs use different file system locations for System WebView.

As said, two known location would be `/system/app/webview` (as mentioned on the [Bromite wiki page}(https://github.com/bromite/bromite/wiki/Installing-SystemWebView)) and `/system/system/product/app/webview` (as it was on my OnePlus 6 with LOS 16 for microG).

I don't think it really is a ROM issue and that the ROM maintainer is at fault with this, but more likely that the Magisk module has to take several supported file system paths to `webview.apk` into consideration when installing.

Although I was unable to find the file system location of `webview.apk` in ArrowOS 11 so far, it's definitely placed at a supported location because otherwise it would not work.

**Comment by ProblematicDude** [comment] 2021-02-20 13:51
> > I'm also A11 user and it's working fine for me. It might be your ROM issue. Contact your maintainer may be.
> 
> It's odd but as it seems different ROMs use different file system locations for System WebView.
> 
> As said, two known location would be `/system/app/webview` (as mentioned on the [Bromite wiki page}(https://github.com/bromite/bromite/wiki/Installing-SystemWebView)) and `/system/system/product/app/webview` (as it was on my OnePlus 6 with LOS 16 for microG).
> 
> I don't think it really is a ROM issue and that the ROM maintainer is at fault with this, but more likely that the Magisk module has to take several supported file system paths to `webview.apk` into consideration when installing.
> 
> Although I was unable to find the file system location of `webview.apk` in ArrowOS 11 so far, it's definitely placed at a supported location because otherwise it would not work.

I never said it's maintainer fault >.< . I meant that,  you ask maintainer if he know anything about this.

**Comment by Master0ne** [comment] 2021-02-20 20:30
Well, the correct patch to `webview.apk` on ArrowOS 11 is `/product/app/webview/`

@androidacy, can you incorporate that into the module's configuration?

**Comment by androidacy** [comment] 2021-02-20 22:08
> Well, the correct patch to `webview.apk` on ArrowOS 11 is `/product/app/webview/`
> 
> @androidacy, can you incorporate that into the module's configuration?

The module already tries to autodetect correct location, but on some roms with weird configurations this fails. It's being reworked in internal testing.

**Comment by Master0ne** [comment] 2021-02-21 03:32
> > Well, the correct patch to `webview.apk` on ArrowOS 11 is `/product/app/webview/`
> > @androidacy, can you incorporate that into the module's configuration?
> 
> The module already tries to autodetect correct location, but on some roms with weird configurations this fails. It's being reworked in internal testing.

@androidacy Thanks a lot, can't await to test it once ready.

**Comment by Master0ne** [comment] 2021-02-23 03:26
@androidacy, in case it matters, the POCO X3 NFC uses dynamic "super" partitions and `/product` is an own partition.

I do not assume that the ArrowOS team chose a weird configuration, it all must come from somewhere. Here is the exact reply from one of the ArrowOS maintainers:

> VANILLA buildtype has Chromium webview, locate in `/product/app/webview`.  
> GAPPS buildtype has Google webview, locate in `/product/app/WebViewGoogle` (WebViewGoogle-Stub).

I hope that information helps in making your module even more versatile and I'm really looking forward in being able to use Bromote SystemWebView on my new phone again.

**Comment by Master0ne** [comment] 2021-02-24 15:35
@androidacy, would it be possible to make the path to `webview.apk` configurable in `config.txt`?

**Comment by Master0ne** [comment] 2021-02-25 17:19
@androidacy, I have just given `Webview Switcher v7.3.0 (4028)` another try on my POCO X3 NFC with ArrowOS 11 and although the path to webview.apk (`/product/app/webview`) was indeed detected correctly after all, it just did not work, so after a successful installation it was still the stock (Chromium) Android System Webview in use.

Please see the attached [**install.log**](https://github.com/Magisk-Modules-Repo/bromitewebview/files/6044712/install.log) (I had to go for `OFFLINE=true` because signature verification failed, no idea why).

**Comment by androidacy** [comment] 2021-03-24 16:10
Support has been added in the 8.x series and 8.1.0 (currently in beta and only available from dl.androidacy.com) refined said support.

**Closed by androidacy** 2021-03-24 16:11 UTC
