### ISSUE TITLE
FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk

### ISSUE THREAD

**Issue by TeslaBargain** [Magisk-Modules-Repo/bromitewebview#5] opened 2019-09-30 11:43 UTC
I'm sorry if I'm wrong here, I don't know if this is an issue concerning the Magisk module and the way Bromite SystemWebView is installed systemless-ly or because of a problem with Bromite SystemWebView itself, which is why I have opened the issue here:

[**FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk**](https://github.com/bromite/bromite/issues/380]

I assumed it's possible to have more than one System WebView installed, but with the Magisk module for Bromite SystemWebView installation it's either Bromite SystemWebView or the regular Android System WebView but not both.

**Comment by TeslaBargain** [comment] 2019-09-30 11:46
For some reason I can not edit the previous comment to correct the link, so here I try again:

[**FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk**](https://github.com/bromite/bromite/issues/380)

**Comment by TeslaBargain** [comment] 2019-10-01 02:52
With the original issue having been closed as off topic I am really hoping that someone here can give more insight about what may be wrong in that case as I have ran out of ideas what else to try.

So how can I install another System WebView in addition to the Bromite one when having installed the Bromite one systemless-ly using that Magisk module?

**Comment by TeslaBargain** [comment] 2019-10-01 04:17
Issue confirmed:

I have uninstalled the Bromite Systemless Webview Magisk module, installed Bromite System Webview directly to `/system/app/webview` and the Bromite SystemWebview apk file as you would for any other app (as per the original install instructions from the [Bromite Wiki](https://github.com/bromite/bromite/wiki/Installing-SystemWebView)) and the error is gone.

To cross check, I have reverted to the original `/system/app/webview/webview.apk`, reinstalled the Bromite Systemless Webview Magisk module, installed the Bromite SystemWebview apk file as you would for any other app, and the error is back.

It would be really great to have that problem fixed, because I'm using LOS 16 for microG with weekly updates, and obviously it's cumbersome when not having a working Magisk method for just keeping Bromite System Webview systemless-ly.

**Comment by alexa-v2** [comment] 2019-10-01 13:00
In that case, just delete the files under $MODPATH/vendor/overlay as I'm pretty sure that's what is causing the issue
That overlay needs to be made more dynamic but I need to work out how

**Comment by alexa-v2** [comment] 2019-10-01 13:03
> 
> 
> For some reason I can not edit the previous comment to correct the link, so here I try again:
> 
> [**FATAL EXCEPTION: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk**](https://github.com/bromite/bromite/issues/380)
@TeslaBargain do not open issues with the module on official bromite repo, @csagan5 and I had a little disagreement over the curl binaries included in the module and he doesn't like me very much. But that log is actually the first helpful one I've gotten

Is there anything under $MODPATH/vendor/overlay?

**Comment by alexa-v2** [comment] 2019-10-01 13:04
Also it's not possible to have both webviews, they both have the same package name

**Comment by alexa-v2** [comment] 2019-10-01 13:06
@TeslaBargain I need the debug install logs from /sdcard

**Comment by TeslaBargain** [comment] 2019-10-01 13:39
@alexa-v2 Thanks for getting back to me that quickly.

I wasn't sure if this issue was caused by Bromite System WebView itself or the Magisk module which is why I filed the issue at @csagan5's repo first. Of course @csagan5 was right as I was able to confirm that the problem is with the Magisk module.

I'm not a developer or seasoned Android user, so please let me know in more details on how to be able to help diagnose the problem.

If you want to give it a try yourself, simply install the [DKB-TAN2go](https://play.google.com/store/apps/details?id=com.starfinanz.mobile.android.dkbpushtan) app and try to open it with the Bromite System WebView installed by Magisk module, which should crash with the shown error right at start.

Where exactly is $MODPATH and is it save to delete files in $MODPATH/vendor/overlay? Can it be done in TWRP or do I need a root file explorer?

I already found out that I do not need more than one System WebView as the TAN2go app is working as expected with the Bromite System WebView installed to /system/app/webview directly.

I don't have my phone at hands right now. Am I assuming correctly that the debug install log is created automatically in /sdcard without anything else to be done? If yes, I will provide the install log as soon as I get back later today.

**Comment by csagan5** [comment] 2019-10-01 17:46
> @csagan5 and I had a little disagreement over the curl binaries included in the module and he doesn't like me very much.

You have had a (1) [really not good reaction](https://github.com/bromite/bromite/issues/341#issuecomment-513553159) and (2) have stated clearly that for you it is ok to compromise building from sources with being able to package quickly: https://github.com/bromite/bromitewebview/issues/4#issuecomment-513487283

For these reasons there will be no collaboration, and most importantly for reason (2), not because of "liking"; see also: https://wiki.debian.org/ReproducibleBuilds

**Comment by TeslaBargain** [comment] 2019-10-01 19:07
@alexa-v2, here is the requested [bromitewebview-debug.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/3678074/bromitewebview-debug.log)

**Comment by alexa-v2** [comment] 2019-10-03 03:40
@csagan5 you really must understand that I couldn't just break the module until I could reproduce those builds. Later on I provided you with the information on how to build it, you promptly rejected it and refused to go with the information provided. The script at the repo provided does actually work, I've tried it now. If you have a preferred method to reproduce the builds or build it your/myself, I am open to any ideas

And I really am sorry about the comments, they were said out of frustration, not just at you. (Never test stuff on your daily driver device, I was up to 1am that night). 

I will be more than happy to work with you if you think there's a chance we can work things out. I made a promise to my users that I'd get this official, and godd*mnit I have broken too many promises in my life

**Comment by alexa-v2** [comment] 2019-10-03 03:42
Thanks @TeslaBargain I'll look at them in the morning. Was offline for a couple days

**Comment by alexa-v2** [comment] 2019-10-03 03:49
@csagan5 and please be assured that I do agree with you. In every case possible, I should be able to reproduce your builds and have a way of ensuring integrity. And although initially the ability to reproduce these builds was in doubt I have provided and tested the used scripts.

To be honest, as soon as I can get `wget` to work with ssl sites I intend to switch to using the built in BusyBox. But I need to figure out how to get it to play nicely with SSL and how to dynamically determine the latest version of bromite to download

**Comment by Master0ne** [comment] 2019-10-06 03:39
@alexa-v2, any news?

The weekly update of LOS for microG is coming soon and with it the new extended routine to install Bromite System WebView directly to `/system/app/webview` with the Magisk module not doing its thing correctly.

**Comment by alexa-v2** [comment] 2019-10-11 01:30
Sorry it took me so long to respond lol
where is your webview located by default? /system/app or what?

And can you verify if the overlay is actually in $MODPATH/vendor/overlay?

**Comment by alexa-v2** [comment] 2019-10-11 01:31
@TeslaBargain @Master0ne

**Comment by TeslaBargain** [comment] 2019-10-11 04:40
@alexa_v2, yes, webview is in /system/app and that's where I replace it with the Bromite System WebView once a week since I can not use your module anymore, using TWRP.

I don't know what $MODPATH is and how to check if the overlay is actually in $MODPATH/vendor/overlay.

Did you try to install the mentioned app ([DKB TAN2go](https://play.google.com/store/apps/details?id=com.starfinanz.mobile.android.dkbpushtan) to see what it does on your phone with your Bromite System WebView Magisk module installed?

If you can replicate the problem, it would be way easier for you to track down the problem. If you can not replicate the problem, there must be something strangely different on your phone or the ROM that you use (I have confirmed the issue on a OnePlus 5 and a OnePlus 6, both are running the latest LineageOS for microG with Magisk).

**Comment by alexa-v2** [comment] 2019-10-11 12:36
@TeslaBargain I'm deving on a moto z3 play - No Q ROMs yet

$MODPATH is the magisk variable for module path, just got used to using it lol

Something has to have changed in 10 but I don't know what. Need a device for that, eying the oneplus 7t when it comes to the US but that's expensive so it may be a bit. Because moto z3 play will probably never get 10 to test on stock ROMs

**Comment by TeslaBargain** [comment] 2019-10-11 13:01
LineageOS 16 for microG is based on Android 9, so that's not the problem.

I guess it really would be easiest if you could just try to start the mentioned app and see what happens, because I'm really not that experienced and don't have your module in use anymore due to this problem.

Otherwise please explain how I can verify if the overlay is actually in $MODPATH/vendor/overlay and I'll have a look at the beginning of the week when the next update of LOS for microG is due.

**Comment by alexa-v2** [comment] 2019-10-11 13:20
@TeslaBargain I literally mean check it's there

In the modules vendor/overlay directory an apk should be present

Also FYI I don't use microg but I've checked on regular lineage

**Comment by TeslaBargain** [comment] 2019-10-11 14:07
I honestly have no idea what I'm doing. I have no root explorer or terminal installed, and checking with the file explorer in TWRP does not seem to be working, as I don't know where the modules vendor/overlay directory is (I guess you didn't mean to mount the vendor partition and then check the content of /vendor/overlay, which contains some other files).

microG has nothing to do with that problem, so if you check on regular LineageOS you should see the exact same issue when trying to start the DKB TAN2go app.

**Comment by alexa-v2** [comment] 2019-10-11 14:09
MODPATH is /data/adb/modules/<modulename>

And P. S. I don't support specific apps. There are ones that will not work without Chrome as the default webview. Let's focus on the FATAL EXCEPTION issue

**Comment by alexa-v2** [comment] 2019-10-11 14:10
@TeslaBargain I highly recommend Mixplorer, there's a free version. Make sure allow root operations in settings is checked

**Comment by TeslaBargain** [comment] 2019-10-11 14:20
Did the submitted log not help? I just took a look at some paths from the log:

`/data/adb/modules_update/bromitewebview/system/vendor/overlay/treble-overlay-webview.apk`

is present, as is

`/data/adb/modules_update/bromitewebview/system/app/webview/webview.apk`

Is that what you wanted to know?

I understand that you can not support specific apps, but in this case it is not the problem that DKB TAN2go does not work without Chrome as the default webview, because installing Bromite System WebView manually to `/system/app/webview` solved the problem and made the TAN2go app work again.

I have just reinstalled your Bromite magisk module (despite the Bromite System WebView already being installed manually) and the TAN2go app keeps crashing on start again with the shown error, with the module removed the error is gone and TAN2go works again (with the Bromite System WebView installed to `/system/app/webview`).

There surely must be an explanation for this.

**Comment by TeslaBargain** [comment] 2019-10-11 14:32
So I have just used a root explorer (Amaze from the F-Droid repo) and had a look for `/vendor/overlay/treble-overlay-webview.apk` which is present. Maybe is has the wrong permissions?

Amaze shows

- Owner: Read / Write
- Group: Read
- Other: Read

I'm really just poking around here without any real idea what I'm doing. If you can give specific instructions on what to try and what to look for, I'll give it my best try.

**Comment by alexa-v2** [comment] 2019-10-11 14:56
@TeslaBargain should be 644 with owner/group root

**Comment by alexa-v2** [comment] 2019-10-11 14:59
Hmm why is it looking in modules_update though? It shouldn't be

And I need a logcat of the crash. Lineage should provide an option to copy the log on app crash, and you need to capture a full log

**Comment by alexa-v2** [comment] 2019-10-11 15:00
New update to 4.1 with 561117025a9280895be9055bf9dea0d3df4565b0 check it

**Comment by TeslaBargain** [comment] 2019-10-11 15:39
It was not looking in modules_update, I did with the root explorer. 

The new update to 4.1 did not change anything, still the same fatal exception. Here is the logcat of the crash:

````
FATAL EXCEPTION: main
Process: com.starfinanz.mobile.android.dkbpushtan, PID: 7080
java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5891)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk
	at jvduvnfw.ItgtGofS.AZkPsqDr(Unknown Source:44)
	at jvduvnfw.ItgtGofS.tG06FdZl(Unknown Source:6)
	at ald.<clinit>(Unknown Source:0)
	... 13 more
Caused by: java.io.FileNotFoundException: File doesn't exist: /vendor/overlay/treble-overlay-webview.apk
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:152)
	at java.util.zip.ZipFile.<init>(ZipFile.java:123)
	at jvduvnfw.MnnIf4jK.yMIt8AfT(Unknown Source:2)
	at jvduvnfw.MnnIf4jK.qW1vF0h8(Unknown Source:115)
	at jvduvnfw.MnnIf4jK.<init>(Unknown Source:12)
	at jvduvnfw.ItgtGofS.ez0AMo8A(Unknown Source:2)
	at jvduvnfw.ItgtGofS.AZkPsqDr(Unknown Source:24)
	... 15 more
````

**Comment by TeslaBargain** [comment] 2019-10-11 15:51
To me as a non-developer this is a mystery. The app crashes because it can not access `/vendor/overlay/treble-overlay-webview.apk` but that file is there with permissions 644 (when your module is installed).

I have just uninstalled your module and that app is working again (with Bromite System WebView still installed manually) although the file `/vendor/overlay/treble-overlay-webview.apk` is gone now (with your module uninstalled).

What exactly is the point of `/vendor/overlay/treble-overlay-webview.apk` when the Bromite System WebView is installed as `/system/app/webview/webview.apk` when installing it manually?

So the problem of the app crashing seems to be the presence of `/vendor/overlay/treble-overlay-webview.apk` when installing your module. Is it save to omit that file and can you try with another update to your module?

**Comment by alexa-v2** [comment] 2019-10-11 16:04
Hey @TeslaBargain are you using magisk hide on the app by any chance?

**Comment by alexa-v2** [comment] 2019-10-11 16:05
@TeslaBargain that overlay is how I get it working on stock

I haven't yet found a reliable way to determine if the module is being installed on stock or custom

**Comment by TeslaBargain** [comment] 2019-10-11 16:51
Yes, Magisk Hide is used on that that app (being a bank app, it wont work otherwise).

I don't follow why it would make a difference if installed on a stock or custom ROM, but the question is now why `/vendor/overlay/treble-overlay-webview.apk` is used by your module at all as that file is not there when installing Bromite System WebView directly to `/system/app/webview/webview.apk`.

As shown, the TAN2go app works with `/vendor/overlay/treble-overlay-webview.apk`not present, and crashes with `/vendor/overlay/treble-overlay-webview.apk` being present due to the use of your module, claiming that file doesn't exist although it is there.

**Comment by alexa-v2** [comment] 2019-10-11 18:09
Two things @TeslaBargain 
1) As previously stated it's what makes stock ROMs accept `com.android.webview` (bromite) as a webview. It overlays the relevant res/xml values
2) If you magisk hide it then yes it'll crash because it hides the overlay from it. It tried to find the overlay and failed because magisk hid it.

I'm going to keep this issue open as it indicates that logic needs reevaluated

**Comment by alexa-v2** [comment] 2019-10-11 18:10
So yes @TeslaBargain as far as the app is aware that file isn't there

I highly recommend you look at the magisk documentation, fascinating stuff

**Comment by TeslaBargain** [comment] 2019-10-12 03:57
Too bad, I was hoping for an easy fix. Sticking to updating it in `/system/app/webview` then. And how strange that nobody else seems to have this problem, because I'm sure the majority of users has the one or other app that needs Magisk hiding. Hopefully you will be able to find a solution to this problem eventually. Thanks for looking into the issue.

**Comment by alexa-v2** [comment] 2019-10-12 17:25
@TeslaBargain at some point in the future I am going to change when that overlay is used, eg only on stock. Problem is I need a way to determine whether the module is running on a custom ROM or not

Can you attach your build.prop please?

**Comment by TeslaBargain** [comment] 2019-10-13 09:46
For some reason drag & drop doesn't currently work on this computer, so here is the content of the `build.prop` of my OnePlus 6 with LOS 16 for microG:

````
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=PQ3A.190801.002
ro.build.display.id=lineage_enchilada-userdebug 9 PQ3A.190801.002 eng.root.20191008.041440 dev-keys
ro.build.version.incremental=eng.root.20191008.041440
ro.build.version.sdk=28
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=9
ro.build.version.security_patch=2019-09-05
ro.build.version.base_os=
ro.build.version.min_supported_target_sdk=17
ro.build.date=Tue Oct  8 04:14:11 UTC 2019
ro.build.date.utc=1570508051
ro.build.type=userdebug
ro.build.user=root
ro.build.host=f24c5eeff50c
ro.build.tags=dev-keys
ro.build.flavor=lineage_enchilada-userdebug
ro.build.system_root_image=true
ro.build.ab_update=true
ro.product.model=ONEPLUS A6003
ro.product.brand=OnePlus
ro.product.name=OnePlus6
ro.product.device=OnePlus6
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
ro.product.manufacturer=OnePlus
ro.product.locale=en-US
ro.wifi.channels=
# ro.build.product is obsolete; use ro.product.device
ro.build.product=OnePlus6
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=OnePlus6-user 8.1.0 OPM1.171019.011 273 release-keys
ro.build.fingerprint=OnePlus/OnePlus6/OnePlus6:8.1.0/OPM1.171019.011/06140300:user/release-keys
ro.build.characteristics=default
ro.lineage.device=enchilada
# end build properties

#
# ADDITIONAL_BUILD_PROPERTIES
#
keyguard.no_require_sim=true
ro.carrier=unknown
ro.dalvik.vm.native.bridge=0
audio.offload.min.duration.secs=30
persist.vendor.audio.hac.enable=false
persist.vendor.audio_hal.dsp_bit_width_enforce_mode=24
ro.config.media_vol_steps=25
ro.config.vc_call_vol_steps=7
camera.disable_zsl_mode=true
debug.gralloc.gfx_ubwc_disable=0
debug.sf.enable_hwc_vds=1
debug.sf.latch_unsignaled=1
persist.vendor.color.matrix=2
persist.vendor.cne.feature=1
persist.vendor.dpm.feature=9
persist.dbg.volte_avail_ovr=1
persist.dbg.vt_avail_ovr=1
persist.dbg.wfc_avail_ovr=1
vendor.iop.enable_prefetch_ofr=1
vendor.iop.enable_uxe=0
media.settings.xml=/system/etc/media_profiles_vendor.xml
ro.vendor.qti.core_ctl_max_cpu=4
ro.vendor.qti.core_ctl_min_cpu=2
persist.vendor.radio.bar_fake_gcell=1
persist.vendor.radio.data_con_rprt=1
persist.vendor.radio.data_ltd_sys_ind=1
persist.vendor.radio.force_on_dc=true
persist.vendor.radio.ignore_dom_time=10
ro.telephony.default_network=22,22
persist.vendor.qti.inputopts.enable=true
persist.vendor.qti.inputopts.movetouchslop=0.6
persist.vendor.data.iwlan.enable=true
persist.vendor.data.mode=concurrent
persist.vendor.ssr.restart_level=ALL_ENABLE
ro.treble.enabled=true
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm64.variant=cortex-a75
dalvik.vm.isa.arm64.features=default
dalvik.vm.isa.arm.variant=cortex-a75
dalvik.vm.isa.arm.features=default
dalvik.vm.lockprof.threshold=500
net.bt.name=Android
dalvik.vm.stack-trace-dir=/data/anr
ro.lineage.version=16.0-20191008-microG-enchilada
ro.lineage.releasetype=microG
ro.lineage.build.version=16.0
ro.modversion=16.0-20191008-microG-enchilada
ro.lineagelegal.url=https://lineageos.org/legal
ro.lineage.display.version=16.0-20191008-enchilada
ro.lineage.build.version.plat.sdk=9
ro.lineage.build.version.plat.rev=0
````

**Comment by alexa-v2** [comment] 2019-10-14 01:35
Alright I'm going to reach out to my Telegram group (https://t.me/inlmagisk) to get some other build.prop files so I can compare them and see how I may be able to determine if the module is being installed on stock or custom @TeslaBargain

**Comment by esselunga** [comment] 2019-10-29 16:46
Hi there, I got the same problem.
Here's the log:
[bromitewebview-debug.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/3784730/bromitewebview-debug.log)

Device: Xiaomi Mi 5 Gemini

ROM 1 (bootloop recovery issue): xiaomi.eu rom (android 8.0) (no stock webview, but WebViewGoogle)
ROM 2 (no issues): syberianOs (android 9.0) (stock webview)

**Comment by alexa-v2** [comment] 2019-11-12 00:15
Gonna drop a beta tomorrow to fix this issue hopefully

**Comment by Master0ne** [comment] 2019-11-12 06:38
Cool! So how did you solve the issue?

**Comment by alexa-v2** [comment] 2020-01-02 19:22
Try the latest beta

At the very least on custom ROMs it won't use said overlay at all

**Comment by alexa-v2** [comment] 2020-01-02 19:22
* stable I mean

**Comment by linuxandria** [comment] 2020-02-10 13:51
Everyone please check out 4.4.1 and report back

**Comment by TeslaBargain** [comment] 2020-02-11 09:18
I have just tried again with 4.4.1 but exactly the same problem as initially reported, that one banking app which Magisk is hidden from just crashes on start with your Magisk module installed.

Maybe there is just no solution for apps that Magisk is hidden from?

More details on what I did:

- So I had Bromite SystemWebView installed using the traditional method (copied to `/system/app/webview` manually using TWRP) and everything was working.
- I installed your module v4.4.1 and rebooted.
- Starting said banking app resulted in an immediate crash of that app, so same problem as before.

Or was there something missing? Should I have reinstalled the Bromite SystemWebView APK as a user program after installing your Magisk module (but it was already installed before installing your module)?

I'm sorry but I didn't have any more time to investigate, I had to uninstall the module after that failed attempt and revert to the traditional installation method, because I'm at work and I need that banking app in a working state.

Anybody else able to test, confirm and analyze that matter further?

**Comment by linuxandria** [comment] 2020-02-15 02:55
@TeslaBargain luckily my module has much better logging now.

Flash the module, reboot, wait about 2 minutes and send the contents of /sdcard/bromite/logs

**Comment by TeslaBargain** [comment] 2020-02-15 08:51
[bwv-post.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/4208084/bwv-post.log)
[find.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/4208085/find.log)
[verbose.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/4208086/verbose.log)
[props.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/4208087/props.log)
[bwv-service.log](https://github.com/Magisk-Modules-Repo/bromitewebview/files/4208088/bwv-service.log)

**Comment by linuxandria** [comment] 2020-02-15 15:46
@TeslaBargain wait I thought you had a Sony? Fingerprint is a OnePlus 6

**Comment by TeslaBargain** [comment] 2020-02-15 16:23
@linuxandria no, it has always been about OnePlus (we have two, one OP5 and one OP6).

**Comment by linuxandria** [comment] 2020-02-15 16:28
Wait different issue my bad lol

**Comment by linuxandria** [comment] 2020-02-15 16:31
Anyway I don't have that specific app but my test device is a OnePlus 7 Pro running OOS OB9 so idk what the issue is. Probably just that specific app for some reason loading the overlay.
Short of manually bind mounting the webview overlay on such a way that magiskhide doesn't hide it idk what to do.
For now remove the overlay under /data/adb/bromitewebview/vendor/overlay (I assume you're still on a custom ROM)

**Comment by TeslaBargain** [comment] 2020-02-15 16:39
It certainly is not an issue with that one specific app or the used custom ROM. My guess is that there is just no solution for this using a Magisk Module for any app that Magisk is hidden from, because that is what Magisk Hide is all about, hiding root and anything Magisk including modules installed in Magisk from the app.

I have been using the manual install method for Bromite SystemWebView ever since and it has already become a weekly routine, just a matter of upgrading LineageOS for microG once a week, followed by copying the webview.apk to the /system/app/webview folder using TWRP. Not a big deal anymore, but of course it would have been more convenient with a working Magisk solution.

**Comment by linuxandria** [comment] 2020-02-15 17:02
My point is I've never had an issue with an all trying to load that overlay, especially as the overlay targets Android. So yes, that specific app + the fact that you hide it. Although it is odd the overlay even copies as post-fs-data should remove it so....
Anyhow closing as I'm fresh out of ideas.

**Closed by linuxandria** 2020-02-15 17:02 UTC
Labels: fixed, input-needed

**Comment by frytkisasmaczne** [comment] 2021-02-27 10:07
for me the module just removed all the webviews i had (aosp and chrome) and didn't install any. the files in /system for browser and webview got replaced tho.
also when i enabled remove on the module i got a bootloop, frozen on boot and after a while reboots (not to recovery like the other guy, mine just reboots endlessly every like 30 seconds).
i used that module for removing modules in twrp to disable the remove flag on bromite webview and then it boots.
